export const LOAD_SOUNDS = 'audio/LOAD_SOUNDS'
export const LOAD_SOUNDS_SUCCESS = 'audio/LOAD_SOUNDS_SUCCESS'
export const LOAD_SOUNDS_FAILURE = 'audio/LOAD_SOUNDS_FAILURE'

export const DROP_UPLOADED_SOUND = 'audio/DROP_UPLOADED_SOUND'
export const CLEAR_UPLOADED_SOUND = 'audio/CLEAR_UPLOADED_SOUND'
export const CHANGE_SOUND_NAME = 'audio/CHANGE_SOUND_NAME'
export const UPLOAD_PROGRESS_CHANGE = 'audio/UPLOAD_PROGRESS_CHANGE'
export const UPLOAD_SOUND = 'audio/UPLOAD_SOUND'
export const UPLOAD_SOUND_SUCCESS = 'audio/UPLOAD_SOUND_SUCCESS'
export const UPLOAD_SOUND_FAILURE = 'audio/UPLOAD_SOUND_FAILURE'

export const PLAYER_STATE_CHANGE = 'audio/PLAYER_STATE_CHANGE'
